Tasks section and minor fixes
newrushbolt/praktiki_za_schekoi pull request #11
Opened 2019-11-20 15:33 UTC by cleargray

2019-11-20 16:02 UTC, newrushbolt requested changes

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +    и делает их более читабельными. Делать _set_fact_ в самих тасках стоит только если это **действительно** необходимо
newline

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +    многоуровневых _dict_of_dicts_of_lists_, если вам понадобились подобные вещи -- вероятно что-то в вашей жизни пошло не так и
newline

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +    задуматься о написании своего [фильтра](https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#filter-plugins)
newline
посмотри, как этот файл отображает гитхаб в режиме "view file".

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +    указанием лимита приведёт к некорректному результату или ошибке выполнения.
newline

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +* Иногда требуется обновить _ansible_facts_ после выполнения каких-то настроек на хосте. Для этого существует модуль _setup:_
newline

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +  set_fact:
Не нравится пример с set_fact.
Кажется, что лучше лишний раз не показывать примеры его использования.

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +    к долгому гаданию, какие права доступа были у исходного файла/шаблона и должны ли они быть такими у целевого.
newline

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +    mode: '644'
Ребятки из ansible не рекомендуют использовать неполную форму, только 4х8bit.

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +Недопустимо:
Предлагаю в этой доке сначала показывать неправильный пример, а потом - правильный.

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +Использовтаь raw допустимо только там, где нет и не может быть установлен Python ().
Использовтаь => Использовать

2019-11-20 16:02 UTC, newrushbolt commented on Ansible.md
> +Использовтаь raw допустимо только там, где нет и не может быть установлен Python ().
К чему круглые скопки в конце предложения?

2019-11-20 16:03 UTC, newrushbolt commented
Поправь за моими клешнями contents.py, пожалуйста: замена символа `_` на `-` не требуется.

2019-11-21 07:58 UTC, cleargray commented on Ansible.md
> +  set_fact:
пожалуй, да. уберу этот кусок.

2019-11-21 08:21 UTC, newrushbolt approved these changes

2019-11-21 08:28 UTC, merged