Rewrite code review, middle
newrushbolt/praktiki_za_schekoi pull request #19
Opened 2019-12-03 11:03 UTC by newrushbolt

2019-12-03 11:24 UTC, cleargray requested changes

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +    Зачастую при решении задачи, участник группы может не верно интерпретировать задачу или драматически неверно оценить
Перенос

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +    Неоптимальные алгоритмы, отсутствие идемпотентности и проверок работоспособности,
перенос

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +    Регулярный анализ кода членами группы приводит к тому,
перенос

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +Code review это практика, пришедшая из мира разработчиков. Тем не менее, для code review подходит абсолютно любой код независимо от того,
перенос

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +    Это проще всего, но важно, ибо _теория разбитых окон_
стоит оставить ссылку на вики

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +    что практически все члены группы знакомятся как с новым, так и со старым кодом, что серьезно снижается фактор автобуса.
стоит оставить ссылку на вики

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +* Pre-commit. Когда review проводит до коммита в систему контроля версий, обычно применяется совместно и другими
перенос

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +как они будут слиты в мастер, и могли бы затронуть production или staging.
...и смогут затронуть...

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +    Сливаемые ветки с кодом сразу же соответствуют style guide, что решает большинство вопросов обслуживаемости кода
перенос

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +    Применимо для достаточно крупных задач или полноценных модулей, готовых к встраиванию или автономной работе.
перенос

2019-12-03 11:24 UTC, cleargray commented on Git.md
> +    что практически все члены группы знакомятся как с новым, так и со старым кодом, что серьезно снижается фактор автобуса.
перенос

2019-12-05 07:51 UTC, cleargray requested changes

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +Ниже некоторый список проблем, которые code review "в вакуме" призван решить:
в вакууме

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +Ниже некоторый список проблем, которые code review "в вакуме" призван решить:
и мне всё же не нравится словосочетание "некоторый список проблем". корявое оно какое-то. может оставить просто  "список проблем" или "список основных проблем". Или "ниже описаны некоторые проблемы"

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +    Это проще всего, но важно, ибо [_теория разбитых окон_](https://lurkmore.to/%D0%A2%D0%B5%D0%BE%D1%80%D0%B8%D1%8F_%D1%80%D0%B0%D0%B7%D0%B1%D0%B8%D1%82%D1%8B%D1%85_%D0%BE%D0%BA%D0%BE%D0%BD)
ссылка на лурк? серьёзно? может хотя бы вики (https://ru.wikipedia.org/wiki/Теория_разбитых_окон)?

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +Если группа не очень большая, то review проводится всеми членами комманды,
команды

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +при этом не нужно страдать параноей, контрольной группы членов комманды достаточно.
команды

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +    Code review - важная работа, не нужно воспринимать это как что-то,
перенос

2019-12-05 07:51 UTC, cleargray commented on Git.md
>     последствии приводит к более быстрому бутстрапу новичков и к единообразию подходов и технических решений, что в свою
поправь сразу переносы в этом куске

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +* Механизмы получения, ферификации и обработки информации из внешних источников
верификации

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +В разных командах это устроенно по разному, почти всегда это отражено в style guide или wiki рядом.
устроено

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +    Подразумевает использованием инструментов для коллективного review: gitlab/github/etc
использование

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +    Аттавизм, практически не используется в современных командах.
атавизм

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +    Если реквест "висит" без review продолжитльное время, то результат работы вашего коллги не может быть использован.
коллеги

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +    Применимо для достаточно крупных задач или полноценных модулей,
перенос

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +    Сливаемые ветки с кодом сразу же соответствуют style guide,
перенос

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +    Зачастую при решении задачи, участник группы может не верно интерпретировать задачу
перенос

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +Тем не менее, для code review подходит абсолютно любой код независимо от того,
перенос

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +В идеале инспектируется весь код, но идеал зачастую не достижим,
недостижим

2019-12-05 07:51 UTC, cleargray commented on Git.md
> +В идеале инспектируется весь код, но идеал зачастую не достижим,
перенос

2019-12-05 07:57 UTC, newrushbolt commented on Git.md
> +    Это проще всего, но важно, ибо [_теория разбитых окон_](https://lurkmore.to/%D0%A2%D0%B5%D0%BE%D1%80%D0%B8%D1%8F_%D1%80%D0%B0%D0%B7%D0%B1%D0%B8%D1%82%D1%8B%D1%85_%D0%BE%D0%BA%D0%BE%D0%BD)
Серьезно.  
На вики ультранудно, никто не будет это читать.

2019-12-05 08:27 UTC, cleargray approved these changes

2019-12-05 08:27 UTC, merged