Feature/playbooks section
newrushbolt/praktiki_za_schekoi pull request #22
Opened 2019-12-06 14:17 UTC by cleargray

2019-12-09 06:17 UTC, newrushbolt requested changes

2019-12-09 06:17 UTC, newrushbolt commented on Ansible.md
> +    * [Антипаттерны установки](#антипаттерны-установки)
Вижу, что ты подключил спеллчекер.  
Допиши плз в readme и .gitlab-ci.yml инструкции для него.

2019-12-09 06:17 UTC, newrushbolt commented on Ansible.md
> +- hosts: vmware_hosts
Кажется, что это не самый удачный пример: прогон по одним и тем же хостам одной и той же роли, но с параметром, который на что-то влияет.

2019-12-09 06:22 UTC, cleargray commented on Ansible.md
> +    * [Антипаттерны установки](#антипаттерны-установки)
он vscode-specific, так что особог смысла писать инструкцию нет

2019-12-11 09:35 UTC, newrushbolt approved these changes

2019-12-11 10:48 UTC, merged