New: defaults
newrushbolt/praktiki_za_schekoi pull request #25
Opened 2019-12-16 08:39 UTC by HappyFX

2019-12-16 08:49 UTC, newrushbolt requested changes

2019-12-16 08:49 UTC, newrushbolt commented on Ansible.md
> +#### Defaults-переменные
Данный пункт покрывает не все про дефолты, а только один конкретный случай с использованием словарей.  
Думаю, что нужно соответствующе назвать этот пункт, и в тексте чуть более сфокусироваться на конкретном случае.

2019-12-16 08:49 UTC, newrushbolt commented on Ansible.md
> +```yaml
А как понять, когда допустимо использовать словари, а когда - нет?

2019-12-16 10:10 UTC, cleargray requested changes

2019-12-16 10:10 UTC, cleargray commented on Ansible.md
> +Если возможно изменение вне словаря значений их надо делать легко доступными и не требующие переопределения/дублирования всего dictionary.
запятая после "значений"

2019-12-16 10:10 UTC, cleargray commented on Ansible.md
> +Переменные в _корень\_роли/defaults/main.yml_ надо определять так, что бы её можно было переопределить в других местах host_vars, group_vars.
...их можно было...

"чтобы" слитно

2019-12-16 11:53 UTC, cleargray requested changes

2019-12-16 11:53 UTC, cleargray commented on Ansible.md
> +Переменные в _корень\_роли/defaults/main.yml_ надо определять так, чтобы её можно было переопределить в других местах host_vars, group_vars.
Respect it harder!
"...так, чтобы **их** можно было..."

2019-12-16 13:37 UTC, cleargray approved these changes

2019-12-18 08:41 UTC, HappyFX commented
https://github.com/newrushbolt/praktiki_za_schekoi/pull/27

2019-12-18 08:41 UTC, closed without merging